ALTER TABLE espacio_colaborativo DROP CONSTRAINT IF EXISTS espacio_colaborativo_id_usuario_creador_fkey;
ALTER TABLE miembro_espacio DROP CONSTRAINT IF EXISTS miembro_espacio_id_espacio_fkey;
ALTER TABLE miembro_espacio DROP CONSTRAINT IF EXISTS miembro_espacio_id_usuario_fkey;
ALTER TABLE tarea DROP CONSTRAINT IF EXISTS tarea_id_usuario_fkey;
ALTER TABLE tarea DROP CONSTRAINT IF EXISTS tarea_id_espacio_fkey;
ALTER TABLE tarea DROP CONSTRAINT IF EXISTS tarea_id_recurrencia_fkey;
ALTER TABLE nota DROP CONSTRAINT IF EXISTS nota_id_usuario_fkey;
ALTER TABLE recordatorio DROP CONSTRAINT IF EXISTS recordatorio_id_tarea_fkey;
ALTER TABLE notificacion DROP CONSTRAINT IF EXISTS notificacion_id_usuario_fkey;
ALTER TABLE notificacion DROP CONSTRAINT IF EXISTS notificacion_id_tarea_fkey;

ALTER TABLE usuario ALTER COLUMN id_usuario TYPE BIGINT;
ALTER TABLE espacio_colaborativo ALTER COLUMN id_espacio TYPE BIGINT;
ALTER TABLE espacio_colaborativo ALTER COLUMN id_usuario_creador TYPE BIGINT;
ALTER TABLE miembro_espacio ALTER COLUMN id_miembro TYPE BIGINT;
ALTER TABLE miembro_espacio ALTER COLUMN id_espacio TYPE BIGINT;
ALTER TABLE miembro_espacio ALTER COLUMN id_usuario TYPE BIGINT;
ALTER TABLE recurrencia ALTER COLUMN id_recurrencia TYPE BIGINT;
ALTER TABLE tarea ALTER COLUMN id_tarea TYPE BIGINT;
ALTER TABLE tarea ALTER COLUMN id_usuario TYPE BIGINT;
ALTER TABLE tarea ALTER COLUMN id_espacio TYPE BIGINT;
ALTER TABLE tarea ALTER COLUMN id_recurrencia TYPE BIGINT;
ALTER TABLE nota ALTER COLUMN id_nota TYPE BIGINT;
ALTER TABLE nota ALTER COLUMN id_usuario TYPE BIGINT;
ALTER TABLE recordatorio ALTER COLUMN id_recordatorio TYPE BIGINT;
ALTER TABLE recordatorio ALTER COLUMN id_tarea TYPE BIGINT;
ALTER TABLE notificacion ALTER COLUMN id_notificacion TYPE BIGINT;
ALTER TABLE notificacion ALTER COLUMN id_usuario TYPE BIGINT;
ALTER TABLE notificacion ALTER COLUMN id_tarea TYPE BIGINT;

ALTER TABLE espacio_colaborativo ADD CONSTRAINT espacio_colaborativo_id_usuario_creador_fkey FOREIGN KEY (id_usuario_creador) REFERENCES usuario(id_usuario);
ALTER TABLE miembro_espacio ADD CONSTRAINT miembro_espacio_id_espacio_fkey FOREIGN KEY (id_espacio) REFERENCES espacio_colaborativo(id_espacio);
ALTER TABLE miembro_espacio ADD CONSTRAINT miembro_espacio_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE tarea ADD CONSTRAINT tarea_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE tarea ADD CONSTRAINT tarea_id_espacio_fkey FOREIGN KEY (id_espacio) REFERENCES espacio_colaborativo(id_espacio);
ALTER TABLE tarea ADD CONSTRAINT tarea_id_recurrencia_fkey FOREIGN KEY (id_recurrencia) REFERENCES recurrencia(id_recurrencia);
ALTER TABLE nota ADD CONSTRAINT nota_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE recordatorio ADD CONSTRAINT recordatorio_id_tarea_fkey FOREIGN KEY (id_tarea) REFERENCES tarea(id_tarea);
ALTER TABLE notificacion ADD CONSTRAINT notificacion_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario);
ALTER TABLE notificacion ADD CONSTRAINT notificacion_id_tarea_fkey FOREIGN KEY (id_tarea) REFERENCES tarea(id_tarea);
